[package]
name = "FinSc-Chemistry-Wiki"
version = "0.1.0"
ipkg = "FinSc-Chemistry-Wiki.ipkg"

[custom.all.idris2-QuickCheck]
type = "local"
path = "../idris2-QuickCheck"
ipkg = "idris2-QuickCheck.ipkg"

[custom.all.FinSc-Multiset-Core]
type = "local"
path = "../FinSc-Multiset-Core"
ipkg = "FinSc-Multiset-Core.ipkg"

[custom.all.FinSc-Chemistry]
type = "local"
path = "../FinSc-Chemistry"
ipkg = "FinSc-Chemistry.ipkg"
